sudo: false

language: node_js

node_js:
  - "10"

dist: trusty

cache:
  directories:
    - node_modules

before_install:
  - npm i -g @angular/cli@8.3.12

script:
  - ng build --prod --base-href="https://solareenlo.com/what-is-blockchain/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/what-is-blockchain
  on:
    branch: master
